import { FormEvent, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowLeft, LockKeyhole } from "lucide-react";
import { getProduct, useShop } from "../context/ShopContext";
import type { Customer } from "../types";

const money = new Intl.NumberFormat("en-MN", { style: "currency", currency: "MNT", maximumFractionDigits: 0 });
const fields: Array<{ key: keyof Customer; label: string; type?: string; autoComplete: string }> = [
  { key: "name", label: "Full name", autoComplete: "name" }, { key: "email", label: "Email address", type: "email", autoComplete: "email" }, { key: "phone", label: "Phone number", type: "tel", autoComplete: "tel" }, { key: "address", label: "Delivery address", autoComplete: "street-address" }, { key: "city", label: "City / district", autoComplete: "address-level2" }, { key: "postalCode", label: "Postal code", autoComplete: "postal-code" },
];
export default function Checkout() {
  const { cart, subtotal, checkout } = useShop(); const navigate = useNavigate();
  const [values, setValues] = useState<Customer>({ name: "", email: "", phone: "", address: "", city: "", postalCode: "" }); const [error, setError] = useState("");
  const shipping = subtotal >= 250000 ? 0 : 15000;
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (cart.length === 0) return setError("Your bag is empty. Add a piece before checking out."); if (Object.values(values).some((value) => !value.trim()) || !/^\S+@\S+\.\S+$/.test(values.email)) return setError("Please complete all delivery details with a valid email address."); const order = checkout(values); navigate(`/payment/${order.id}`, { replace: true }); };
  return <main className="min-h-screen bg-[#080808] text-[#f4f4f4] px-6 md:px-12 py-8 md:py-12"><div className="max-w-6xl mx-auto"><header className="flex justify-between items-center border-b border-white/10 pb-6"><Link to="/" className="flex items-center gap-2 text-[10px] tracking-[.2em] uppercase text-white/60 hover:text-white"><ArrowLeft size={13}/> Return to collection</Link><span className="font-display font-bold text-sm">SADCREAM</span><span className="text-[9px] font-mono tracking-widest text-white/40">SECURE CHECKOUT</span></header><form onSubmit={submit} className="grid lg:grid-cols-12 gap-12 mt-12"><section className="lg:col-span-7"><p className="text-[10px] tracking-[.35em] font-mono text-white/40">01 // DELIVERY INFORMATION</p><h1 className="font-display text-3xl md:text-4xl mt-3">CONFIRM YOUR DETAILS</h1><div className="grid sm:grid-cols-2 gap-4 mt-8">{fields.map((field) => <label key={field.key} className={field.key === "address" ? "sm:col-span-2" : ""}><span className="block text-[10px] tracking-[.15em] uppercase text-white/50 mb-2">{field.label}</span><input required type={field.type ?? "text"} autoComplete={field.autoComplete} value={values[field.key]} onChange={(e) => setValues((current) => ({ ...current, [field.key]: e.target.value }))} className="w-full bg-black border border-white/15 p-3.5 text-sm focus:outline-none focus:border-white/60" /></label>)}</div>{error && <p role="alert" className="mt-4 text-xs text-red-300">{error}</p>}<button type="submit" className="mt-8 w-full sm:w-auto bg-white text-black px-8 py-4 text-[10px] font-bold tracking-[.25em] uppercase inline-flex items-center justify-center gap-2"><LockKeyhole size={13}/> Continue to payment</button></section><aside className="lg:col-span-5 bg-white/[.03] border border-white/10 p-6 h-fit"><p className="text-[10px] tracking-[.35em] font-mono text-white/40">ORDER SUMMARY</p><div className="divide-y divide-white/10 mt-5">{cart.map((line) => { const product = getProduct(line.productId); return product && <div key={`${line.productId}-${line.size}`} className="py-4 flex gap-4"><img src={product.primaryImage} alt="" className="w-14 h-18 object-cover"/><div className="grow"><p className="text-xs font-display">{product.name}</p><p className="text-[10px] text-white/40 mt-1">{line.size} · Qty {line.quantity}</p></div><span className="text-xs">{money.format(product.price * line.quantity)}</span></div>; })}</div><div className="border-t border-white/10 mt-2 pt-4 space-y-3 text-sm"><p className="flex justify-between text-white/60"><span>Subtotal</span><span>{money.format(subtotal)}</span></p><p className="flex justify-between text-white/60"><span>Shipping</span><span>{shipping ? money.format(shipping) : "Complimentary"}</span></p><p className="flex justify-between text-base pt-3"><strong>Total</strong><strong>{money.format(subtotal + shipping)}</strong></p></div></aside></form></div></main>;
}
