import { Link } from "react-router-dom";
import { Minus, Plus, ShoppingBag, X } from "lucide-react";
import { getProduct, useShop } from "../context/ShopContext";

const money = new Intl.NumberFormat("en-MN", { style: "currency", currency: "MNT", maximumFractionDigits: 0 });
export default function CartDrawer({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { cart, subtotal, updateQuantity } = useShop();
  if (!open) return null;
  return <><button className="fixed inset-0 bg-black/70 z-40" onClick={onClose} aria-label="Close bag overlay" /><aside className="fixed z-50 right-0 top-0 h-dvh w-full max-w-md bg-[#080808] text-white border-l border-white/10 p-6 md:p-8 flex flex-col" role="dialog" aria-modal="true" aria-label="Shopping bag"><div className="flex items-center justify-between border-b border-white/10 pb-5"><div className="flex items-center gap-3"><ShoppingBag size={16}/><h2 className="text-xs tracking-[.25em] font-mono uppercase">Bag // {cart.length}</h2></div><button onClick={onClose} className="p-2 text-white/60 hover:text-white" aria-label="Close bag"><X size={18}/></button></div>{cart.length === 0 ? <div className="m-auto text-center"><p className="text-white/45 text-sm italic">Your bag is empty.</p><button onClick={onClose} className="mt-6 text-[10px] tracking-[.2em] uppercase border border-white/20 px-5 py-3">Continue exploring</button></div> : <><div className="overflow-auto grow divide-y divide-white/10">{cart.map((line) => { const product = getProduct(line.productId); if (!product) return null; return <div className="py-5 flex gap-4" key={`${line.productId}-${line.size}`}><img className="w-20 h-24 object-cover" src={product.primaryImage} alt=""/><div className="grow"><p className="text-[10px] tracking-wide font-mono text-white/50">{product.id} // {line.size}</p><h3 className="text-xs font-display mt-1">{product.name}</h3><p className="text-xs mt-2">{money.format(product.price)}</p><div className="flex gap-3 mt-3 items-center"><button aria-label="Decrease quantity" onClick={() => updateQuantity(product.id, line.size, line.quantity - 1)}><Minus size={13}/></button><span className="font-mono text-xs">{line.quantity}</span><button aria-label="Increase quantity" onClick={() => updateQuantity(product.id, line.size, line.quantity + 1)}><Plus size={13}/></button></div></div></div>; })}</div><div className="border-t border-white/10 pt-5"><div className="flex justify-between text-sm"><span className="text-white/50">Subtotal</span><strong>{money.format(subtotal)}</strong></div><p className="text-[10px] text-white/35 mt-2">Shipping is calculated at checkout. Complimentary over ₮250,000.</p><Link onClick={onClose} to="/checkout" className="block mt-5 bg-white text-black text-center text-[10px] tracking-[.25em] font-bold uppercase py-4">Secure checkout</Link></div></>}</aside></>;
}
