import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { PRODUCTS } from "../data";
import { readLocal, writeLocal } from "../lib/storage";
import type { CartItem, Customer, Order, Product } from "../types";

interface ShopContextValue { cart: CartItem[]; wishlist: string[]; addToCart: (productId: string, size: string, quantity?: number) => void; updateQuantity: (productId: string, size: string, quantity: number) => void; toggleWishlist: (productId: string) => void; cartCount: number; subtotal: number; checkout: (customer: Customer) => Order; orders: Order[]; updateOrderStatus: (id: string, status: Order["status"]) => void; }
const ShopContext = createContext<ShopContextValue | null>(null);
const CART_KEY = "sadcream.cart"; const WISHLIST_KEY = "sadcream.wishlist"; const ORDER_KEY = "sadcream.orders";
export function ShopProvider({ children }: { children: ReactNode }) {
  const [cart, setCart] = useState<CartItem[]>(() => readLocal(CART_KEY, [])); const [wishlist, setWishlist] = useState<string[]>(() => readLocal(WISHLIST_KEY, [])); const [orders, setOrders] = useState<Order[]>(() => readLocal(ORDER_KEY, []));
  useEffect(() => writeLocal(CART_KEY, cart), [cart]); useEffect(() => writeLocal(WISHLIST_KEY, wishlist), [wishlist]); useEffect(() => writeLocal(ORDER_KEY, orders), [orders]);
  const value = useMemo<ShopContextValue>(() => ({ cart, wishlist, orders, cartCount: cart.reduce((sum, item) => sum + item.quantity, 0), subtotal: cart.reduce((sum, item) => sum + (PRODUCTS.find((p) => p.id === item.productId)?.price ?? 0) * item.quantity, 0), addToCart: (productId, size, quantity = 1) => setCart((current) => { const line = current.find((item) => item.productId === productId && item.size === size); return line ? current.map((item) => item === line ? { ...item, quantity: item.quantity + quantity } : item) : [...current, { productId, size, quantity }]; }), updateQuantity: (productId, size, quantity) => setCart((current) => quantity < 1 ? current.filter((item) => item.productId !== productId || item.size !== size) : current.map((item) => item.productId === productId && item.size === size ? { ...item, quantity } : item)), toggleWishlist: (productId) => setWishlist((current) => current.includes(productId) ? current.filter((id) => id !== productId) : [...current, productId]), checkout: (customer) => { const subtotal = cart.reduce((sum, item) => sum + (PRODUCTS.find((p) => p.id === item.productId)?.price ?? 0) * item.quantity, 0); const shipping = subtotal >= 250000 ? 0 : 15000; const order: Order = { id: `SC-${Date.now().toString(36).toUpperCase()}-${Math.floor(100 + Math.random() * 900)}`, transactionCode: `SCX-${crypto.randomUUID().slice(0, 8).toUpperCase()}`, createdAt: new Date().toISOString(), customer, items: cart, subtotal, shipping, total: subtotal + shipping, status: "pending_verification" }; setOrders((current) => [...current, order]); setCart([]); return order; }, updateOrderStatus: (id, status) => setOrders((current) => current.map((order) => order.id === id ? { ...order, status } : order)), }), [cart, wishlist, orders]);
  return <ShopContext.Provider value={value}>{children}</ShopContext.Provider>;
}
export function useShop(): ShopContextValue { const value = useContext(ShopContext); if (!value) throw new Error("useShop must be used inside ShopProvider"); return value; }
export const getProduct = (id: string): Product | undefined => PRODUCTS.find((product) => product.id === id);
